name: fedora
description: This is fedora image.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43

modules:
# - from-file: kernel-cachyos.yml

  - from-file: common-cleanup.yml
  - from-file: common-packages.yml

  - from-file: common-homebrew.yml
  - from-file: common-flatpaks.yml
  - from-file: common-fonts.yml
  - from-file: common-files.yml

  - from-file: common-systemd.yml
  - from-file: common-scripts.yml

  - from-file: common-signing.yml
