name: fedora
description: This is fedora image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - from-file: common-repository.yml
  - from-file: common-packages.yml
  - from-file: common-homebrew.yml
  - from-file: common-flatpaks.yml
  - from-file: common-signing.yml
