name: fedora
description: This is fedora image.

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42

modules:
  - from-file: common-repository.yml
  - from-file: common-cleanup.yml

  - from-file: desktop-packages.yml
  - from-file: desktop-cleanup.yml
  - from-file: desktop-extensions.yml
  - from-file: desktop-gschema.yml
  - from-file: desktop-scripts.yml

  - from-file: common-packages.yml
  - from-file: common-homebrew.yml
  - from-file: common-flatpaks.yml
  - from-file: common-files.yml
  - from-file: common-fonts.yml
  - from-file: common-justfiles.yml
  - from-file: common-scripts.yml
  - from-file: common-systemd.yml
  - from-file: common-kargs.yml
  - from-file: common-signing.yml