build-users-group = nixbld
auto-optimise-store = true
warn-dirty = false
substituters = https://cache.nixos.org
trusted-substituters = https://cache.nixos.org
keep-outputs = false
build-use-sandbox = true